services:
  mongodb:
    image: mongo:latest
    ports:
      - "127.0.0.1:27017:27017" # Restrict MongoDB to localhost
    volumes:
      - mongodb_data_dev:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    networks:
      - app-network
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=assistant_db
      - MONGODB_USER=assistant_user
      - MONGODB_PASSWORD=assistant_pass
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongo-express:
    image: mongo-express:1.0.2
    ports:
      - "127.0.0.1:8081:8081" # Restrict Mongo Express to localhost
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - app-network
    depends_on:
      mongodb:
        condition: service_healthy

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data_dev:
